Add support for individual palettes per frame.
SkyTheCodeMaster/bimg pull request #1
Opened 2022-05-31 23:30 UTC by MasonGulu

Wording could be adjusted to make it clearer.

2022-05-31 23:50 UTC, MasonGulu commented
Should the palette key be moved from the root of the file? Instead of a palette table of palettes we instead give each frame an optional palette key that contains the palette for that frame?

2022-06-01 00:33 UTC, SkyTheCodeMaster commented
Current discussion in `Image formats` thread in the [MCCM Guild](https://canary.discord.com/channels/477910221872824320/980612236655603752) suggest that instead of ```lua
{
  palette = {
    {
      colour = code
    },
}
```
The following is suggested: ```lua
{
  {
    {"image data","aaaaa0aaaa","ffffffffff"},
    palette = {
      colour = code,
    },
  }
}
``` 
The difference here is that the palette is stored inside of the frame table instead of the root palette table.
The use of the root palette table will be loaded before frames are being drawn, whereas the palette tables inside the frames are set before that specific frame is drawn.

2022-06-01 00:36 UTC, Ocawesome101 commented
i second Sky's thoughts.

2022-06-01 00:42 UTC, MasonGulu commented
I've updated `rough-ideas.md` to match this specification, and adjusted the examples to use the default first frame. The examples may want to be modified to make use of the per-frame palettes.

2022-06-01 00:54 UTC, SkyTheCodeMaster requested changes
Overall looks good, however the specification should be adjusted according to the comments I left.

2022-06-01 00:54 UTC, SkyTheCodeMaster commented on rough-ideas.md
> +Each frame can have a `palette` key to specify a specific palette for that frame, following the rules of the base `palette` key.
This is for *image data*, not metadata. This should be sitting down in the metadata section prepended with `(per frame)`

2022-06-01 00:54 UTC, SkyTheCodeMaster commented on rough-ideas.md
> +`palette`: table Palette table in format of colors api (key: color number - value: EITHER table of 3 ranged 0-1 floats for each RGB component, OR a single item which is the hex-formatted number #RRGG
The optional statement isn't required, as every single one of these metadata flags (save `animation`) are required.

2022-06-01 01:08 UTC, SkyTheCodeMaster approved these changes
Looks good to me, we should await other's opinions before merging this into the standard!

2022-06-01 05:45 UTC, spr2-dev commented
Looks good to me, adding a palette per frame increases flexibility and that's always nice to have.
Should the `version` metadata be increased, as the first deserializers were already made?

2022-06-01 06:02 UTC, MasonGulu commented
`version`'s format hasn't been discussed yet (as far as I'm aware), so I'm not sure that there's anything *to* increment

2022-06-01 08:02 UTC, spr2-dev commented
True, the spec isn't released yet anyway, so the edits made now will count towards the first "official" version of the format.

2022-06-01 11:16 UTC, SkyTheCodeMaster commented
It does seem that a large number of people are in agreeance.
Merging!

2022-06-01 11:16 UTC, merged